---

- hosts: all
  become: true
  tasks:

  - name: install httpd, php support, updates for index .....
    dnf: 
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Rocky" 

 
