---

- hosts: all
  become: true
  tasks:

  - name: install httpd, php support, updates for index .....
    package: 
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes


 
