- hosts: all
  become: true
  roles: 
    - base

- hosts: workstation
  become: true
  roles: 
    - workstation

- hosts: web_server
  become: true
  roles:
    - web_server

- hosts: db_server
  become: true
  roles:
    - db_server 

- hosts: file_server
  become: true
  roles:
    - file_server  
